// Generated by scripts/fetch-wayback-releases.mjs — do not edit by hand.
//
// Esri World Imagery Wayback addresses snapshots by an opaque integer release id, not by
// date. This is the date -> release mapping, one entry per calendar year (the latest release
// in each), resolved from the service's WMTSCapabilities document.
//
// Source: https://wayback.maptiles.arcgis.com/arcgis/rest/services/World_Imagery/WMTS/1.0.0/WMTSCapabilities.xml
// 195 releases published in total; 13 kept.

import type { VariantValue } from "./types";

export const WAYBACK_RELEASES: readonly VariantValue[] = [
  { value: "5844", label: "2014-12-30" },
  { value: "28163", label: "2015-12-16" },
  { value: "18966", label: "2016-12-20" },
  { value: "25521", label: "2017-11-16" },
  { value: "23448", label: "2018-12-14" },
  { value: "4756", label: "2019-12-12" },
  { value: "29260", label: "2020-12-16" },
  { value: "26120", label: "2021-12-21" },
  { value: "45134", label: "2022-12-14" },
  { value: "56102", label: "2023-12-07" },
  { value: "16453", label: "2024-12-12" },
  { value: "13192", label: "2025-12-18" },
  { value: "32246", label: "2026-06-30" },
];

/** The newest kept snapshot — the default when a URL names no variant. */
export const WAYBACK_LATEST = "32246";
